// konversi nilai celcius

// const celcius = 90;
// const rumus = (9 / 5) * celcius + 32;


// console.log(`suhu celcius = ${celcius} dan suhu fahrenheit = ${rumus}`)



let temperaturCelcius ;
let temperaturFahrenheit;


temperaturCelcius = 50;
temperaturFahrenheit = (9 / 5) * temperaturCelcius + 32;


console.log(`suhu celcius = ${temperaturCelcius} dan suhu fahrenheit = ${temperaturFahrenheit}`)

temperaturCelcius = 70;
temperaturFahrenheit = (9 / 5) * temperaturCelcius + 32;


console.log(`suhu celcius = ${temperaturCelcius} dan suhu fahrenheit = ${temperaturFahrenheit}`)

temperaturCelcius = 120;
temperaturFahrenheit = (9 / 5) * temperaturCelcius + 32;


console.log(`suhu celcius = ${temperaturCelcius} dan suhu fahrenheit = ${temperaturFahrenheit}`)